article/urls.py
from django.urls import path
from .views import home, category, article

app_name = 'article'

urlpatterns = [
    path('', home, name="home"),
    path('category/<str:slug>', category, name="category"),
    path('article/<str:slug>', article, name="article"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('article.urls'))
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from django.contrib.auth.models import User
from category.models import Category
# from django.utils import timezone
from datetime import datetime
import time

# Create your models here.
class Article(models.Model):
	title = models.CharField(max_length=250)
	slug = models.SlugField(unique=True)
	summary = models.TextField(max_length=500)
	content = models.TextField()
	image = models.ImageField(null=True, blank=True, upload_to=time.strftime("%Y/%m/%d"))
	category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
	author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
	publish = models.DateTimeField(default=datetime.now())
	created = models.DateTimeField(auto_now=True)
	updated = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.title

	def fullname(self):
		return "{} {}".format(self.author.first_name, self.author.last_name)

	class Meta:
		verbose_name = "مقاله"
		verbose_name_plural = "مقالات"
		ordering = ('-publish',)

category/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
	name = models.CharField(max_length=32, verbose_name="نام دسته")
	slug = models.SlugField(unique=True, verbose_name="آدرس دسته")
	position = models.IntegerField()

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = "دسته بندی"
		verbose_name_plural = "دسته بندی ها"
		ordering = ('id',)

article/views.py
from django.shortcuts import render, get_object_or_404
from category.models import Category
from article.models import Article
from django.http import JsonResponse

# Create your views here.
def home(request):
	categories = Category.objects.all()
	articles = Article.objects.all()
	context = {
		'categories': categories,
		'articles': articles,
	}
	return render(request, 'article/home.html', context)

def article(request, slug):
	article = get_object_or_404(Article, slug=slug)
	categories = Category.objects.all()
	context = {
		'categories': categories,
		'article': article,
	}
	return render(request, 'article/article.html', context)

def category(request, slug):
	categories = Category.objects.all()
	category = get_object_or_404(Category, slug=slug)
	articles = category.article_set.all()
	context = {
		'categories': categories,
		'category': category,
		'articles': articles
	}
	return render(request, 'article/category.html', context)

category/views.py
from django.shortcuts import render

# Create your views here.

article/templates/article/article.html
{% extends 'article/base.html' %}

{% block title %}{{article.title}} - وبلاگ لاگ اردبیل{% endblock %}

{% block main %}
	<article>
		<a href="{% url 'article:article' article.slug %}">{{article.title}}</a>
		{% if article.image %}
			<div>
				<img src="{{article.image.url}}" alt="{{article.title}}">
			</div>
		{% endif %}
		<p>{{article.content}}</p>
		<p>{{article.fullname}}</p>
	</article>
{% endblock %}

article/templates/article/base.html
<!DOCTYPE html>
<html dir="rtl">
<head>
	<title>{% block title %}وبلاگ لاگ اردبیل{% endblock %}</title>
	<meta charset="utf-8">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<style type="text/css">
		body {
			direction: rtl;
			text-align: right;
		}
	</style>
</head>
<body>
	<header>
		<h1><a href="{% url 'article:home' %}">Home</a></h1>
		<nav>
			<ul>
				{% for category in categories %}
					<li><a href="{% url 'article:category' category.slug %}">{{category.name}}</a></li>
				{% endfor %}
			</ul>
		</nav>
	</header>
	<main class="container">
		{% block main %}

		{% endblock %}
	</main>
</body>
</html>

article/templates/article/category.html
{% extends 'article/base.html' %}

{% block title %}دسته‌ی {{category.name}} - وبلاگ لاگ اردبیل{% endblock %}

{% block main %}
	<h2>{{category.name}}</h2>
	{% for article in articles %}
		<article>
			<a href="{% url 'article:article' article.slug %}">{{article.title}}</a>
			<p>{{article.summary}}</p>
		</article>
	{% endfor %}
{% endblock %}

article/templates/article/home.html
{% extends 'article/base.html' %}


{% block main %}
	{% for article in articles %}
		<article>
			<a href="{% url 'article:article' article.slug %}">{{article.title}}</a>
			<p>{{article.summary}}</p>
		</article>
	{% endfor %}
{% endblock %}